"""Genre profiles and style packs (CC5/CC6).

Six genre profiles and ten structured style packs.  A genre is *default*
strategy (user may override); a style pack is structured look fields and is
never bound to a Provider.
"""

from __future__ import annotations

from app.director.creative_capabilities.packs import (
    CameraBehavior,
    DialogDensity,
    GenreProfileSpec,
    MotionFeel,
    ScenePacing,
    StoryRhythm,
    StylePackSpec,
)

# --- Genre profiles -----------------------------------------------------------

GENRE_PROFILES: list[GenreProfileSpec] = [
    GenreProfileSpec(
        genre_key="short_drama_romance_v1",
        genre_version="1",
        display_name="短剧言情",
        description="高浓度情感进展, 快节奏撒糖与冲突交替。",
        story_rhythm=StoryRhythm.PUNCHY,
        scene_pacing=ScenePacing.FAST,
        dialogue_density=DialogDensity.BALANCED,
        hook_strategy="身份/误会开局, 首集抛出关系张力",
        turn_frequency="每 1-2 集一次关系反转",
        shot_pacing="每场景 2-4 镜头",
        preferred_skill_stack=[
            "short-drama-hook-v1",
            "emotional-conflict-v1",
            "emotional-performance-v1",
            "character-consistency-v1",
        ],
        workflow_preferences={"scene_batch": 3, "prefer_dialogue_coverage": True},
        quality_emphasis=["情绪可见", "身份一致", "对白节奏"],
    ),
    GenreProfileSpec(
        genre_key="short_drama_suspense_v1",
        genre_version="1",
        display_name="短剧悬疑",
        description="持续悬念与反转驱动追更。",
        story_rhythm=StoryRhythm.RHYTHMIC,
        scene_pacing=ScenePacing.MEDIUM,
        dialogue_density=DialogDensity.LIGHT,
        hook_strategy="强悬念开场, 信息差制造追问",
        turn_frequency="每集一个反转",
        shot_pacing="每场景 3-5 镜头",
        preferred_skill_stack=[
            "short-drama-hook-v1",
            "suspense-reversal-v1",
            "continuity-guardian-v1",
        ],
        workflow_preferences={"scene_batch": 2, "prefer_subjective_tension": True},
        quality_emphasis=["不提前泄露", "伏笔闭环", "连续性"],
    ),
    GenreProfileSpec(
        genre_key="short_drama_revenge_v1",
        genre_version="1",
        display_name="短剧复仇",
        description="压抑后爆发, 强弱关系反转的爽感节奏。",
        story_rhythm=StoryRhythm.SLOW_BURN,
        scene_pacing=ScenePacing.MEDIUM,
        dialogue_density=DialogDensity.BALANCED,
        hook_strategy="受辱或背叛开局, 埋下反击动机",
        turn_frequency="每 1-2 集一个强弱反转",
        shot_pacing="每场景 3-4 镜头",
        preferred_skill_stack=[
            "short-drama-hook-v1",
            "emotional-conflict-v1",
            "emotional-performance-v1",
        ],
        workflow_preferences={"scene_batch": 3},
        quality_emphasis=["情绪张力", "反转有力", "身份稳定"],
    ),
    GenreProfileSpec(
        genre_key="dynamic_comic_v1",
        genre_version="1",
        display_name="动感漫改",
        description="高饱和、强动态、漫画式分镜。",
        story_rhythm=StoryRhythm.PUNCHY,
        scene_pacing=ScenePacing.FAST,
        dialogue_density=DialogDensity.LIGHT,
        hook_strategy="夸张动作/视觉冲击开场",
        turn_frequency="高频小反转",
        shot_pacing="每场景 4-8 镜头",
        preferred_skill_stack=[
            "action-scene-direction-v1",
            "montage-direction-v1",
            "character-consistency-v1",
        ],
        workflow_preferences={"prefer_action_dynamic": True},
        quality_emphasis=["动态冲击", "角色识别", "分镜张力"],
    ),
    GenreProfileSpec(
        genre_key="commercial_product_v1",
        genre_version="1",
        display_name="商业产品",
        description="突出产品卖点、质感与品牌美学的节奏。",
        story_rhythm=StoryRhythm.STEADY,
        scene_pacing=ScenePacing.MEDIUM,
        dialogue_density=DialogDensity.LIGHT,
        hook_strategy="产品特写开门见山, 卖点前置",
        turn_frequency="低频, 以卖点递进为主",
        shot_pacing="每场景 2-5 镜头",
        preferred_skill_stack=[
            "montage-direction-v1",
            "character-consistency-v1",
        ],
        workflow_preferences={"prefer_commercial_product": True},
        quality_emphasis=["产品质感", "品牌色", "卖点清晰"],
    ),
    GenreProfileSpec(
        genre_key="music_montage_v1",
        genre_version="1",
        display_name="音乐蒙太奇",
        description="以音乐节奏与情绪递进主导的蒙太奇。",
        story_rhythm=StoryRhythm.RHYTHMIC,
        scene_pacing=ScenePacing.FAST,
        dialogue_density=DialogDensity.LIGHT,
        hook_strategy="音乐鼓点开场, 情绪先行",
        turn_frequency="随音乐段落递进",
        shot_pacing="每场景 5-10 镜头",
        preferred_skill_stack=[
            "montage-direction-v1",
            "emotional-performance-v1",
        ],
        workflow_preferences={"prefer_montage_rhythm": True},
        quality_emphasis=["节奏对点", "情绪递进", "镜头语义"],
    ),
]


# --- Style packs --------------------------------------------------------------

STYLE_PACKS: list[StylePackSpec] = [
    StylePackSpec(
        style_key="cinematic_realism_v1",
        style_version="1",
        display_name="电影写实",
        medium="video",
        description="克制、自然光、电影质感。",
        palette={"shadow": "#1a1a1a", "highlight": "#f2efe9", "skin": "#e8b08c"},
        lighting="自然/柔光, 讲求方向与体积",
        contrast="中低, 柔和过渡",
        texture="颗粒细微, 真实材质",
        lens_language="35-50mm 定焦, 呼吸感",
        composition="三分法, 留白克制",
        camera_behavior=CameraBehavior.TRIPOD,
        motion_feel=MotionFeel.WEIGHTED,
        production_design="真实场景, 可信道具",
        post_processing="低饱和, 胶片微噪",
        negative_tendencies=["高饱和霓虹", "过度锐化", "夸张运动"],
        reference_guidance=["参考写实电影剧照", "避免塑料质感"],
    ),
    StylePackSpec(
        style_key="chinese_drama_v1",
        style_version="1",
        display_name="国剧质感",
        medium="video",
        description="克制的东方美学, 重氛围与情绪。",
        palette={"shadow": "#2b2b33", "highlight": "#d8cfc0", "accent": "#8a2f3c"},
        lighting="氛围主光, 情绪化方向光",
        contrast="中等, 明暗层次",
        texture="细腻, 略柔",
        lens_language="50mm 中景为主, 微长焦",
        composition="对称与留白并用",
        camera_behavior=CameraBehavior.STABILIZED,
        motion_feel=MotionFeel.SMOOTH,
        production_design="东方场景细节, 含蓄道具",
        post_processing="暖调, 柔焦微光",
        negative_tendencies=["过度日系滤镜", "强行赛博", "西方场景错位"],
        reference_guidance=["参考国产精品剧", "道具细节可信"],
    ),
    StylePackSpec(
        style_key="film_noir_v1",
        style_version="1",
        display_name="黑色电影",
        medium="video",
        description="高对比、阴影浓重、压抑悬疑。",
        palette={"shadow": "#050505", "highlight": "#e8dcc0", "accent": "#c8a04a"},
        lighting="硬光, 大量百叶窗/烟雾轮廓",
        contrast="高, 深邃阴影",
        texture="粗颗粒, 胶片质感",
        lens_language="广角变形感, 低机位",
        composition="framed 构图, 明暗切割",
        camera_behavior=CameraBehavior.TRIPOD,
        motion_feel=MotionFeel.WEIGHTED,
        production_design="黑暗场景, 霓虹反射, 斑驳墙面",
        post_processing="黑白/去饱和, 颗粒重",
        negative_tendencies=["高亮度日戏", "平光", "鲜艳色"],
        reference_guidance=["参考 40-50 年代黑色电影", "强阴影轮廓"],
    ),
    StylePackSpec(
        style_key="hong_kong_urban_v1",
        style_version="1",
        display_name="港式都市",
        medium="video",
        description="拥挤霓虹、冷暖碰撞、市井张力。",
        palette={"shadow": "#101a2b", "highlight": "#ffd39a", "accent": "#2fd4c9"},
        lighting="霓虹混合, 夜景主调",
        contrast="高, 冷暖冲撞",
        texture="街道尘埃, 玻璃反光",
        lens_language="广角快切, 机位灵动",
        composition="人群/招牌/镜面层次",
        camera_behavior=CameraBehavior.HANDHELD,
        motion_feel=MotionFeel.RHYTHMIC,
        production_design="密集街区, 招牌霓虹, 潮湿夜",
        post_processing="冷青橙, 高对比",
        negative_tendencies=["过度干净", "日系柔光", "低密度街道"],
        reference_guidance=["参考港产动作/市井片", "霓虹冷暖"],
    ),
    StylePackSpec(
        style_key="cyberpunk_neon_v1",
        style_version="1",
        display_name="赛博霓虹",
        medium="video",
        description="未来都市, 高饱和全息霓虹。",
        palette={"shadow": "#04060f", "highlight": "#eafcff", "accent": "#ff2e8a"},
        lighting="霓虹全息, 逆光轮廓",
        contrast="极高, 高光溢出",
        texture="全息/玻璃/电线细节",
        lens_language="广角, 变形, 大光圈",
        composition="纵深未来街景, 几何切割",
        camera_behavior=CameraBehavior.DRONE,
        motion_feel=MotionFeel.FLOATING,
        production_design="未来元素, 全息招牌, 赛博服装",
        post_processing="高饱和, 青品色偏",
        negative_tendencies=["脏乱噪点", "灰色扁平", "真实城市实拍感"],
        reference_guidance=["参考赛博朋克概念", "霓虹主色"],
    ),
    StylePackSpec(
        style_key="chinese_ancient_v1",
        style_version="1",
        display_name="国风古装",
        medium="video",
        description="古装雅致, 服化道与光影东方化。",
        palette={"shadow": "#2e241b", "highlight": "#e9dcc3", "accent": "#7d3b2b"},
        lighting="室内烛光/窗棂漏光, 户外柔光",
        contrast="中, 层次温润",
        texture="织物/木质/宣纸质感",
        lens_language="中长焦, 端庄构图",
        composition="中轴对称, 前景遮挡",
        camera_behavior=CameraBehavior.STABILIZED,
        motion_feel=MotionFeel.SMOOTH,
        production_design="古建筑/服饰/器物, 细节考究",
        post_processing="暖调, 微柔, 少噪",
        negative_tendencies=["西式明亮平光", "现代材质", "自然主义色彩"],
        reference_guidance=["参考古装剧服化道", "器物质感可信"],
    ),
    StylePackSpec(
        style_key="anime_clean_v1",
        style_version="1",
        display_name="清爽动漫",
        medium="video",
        description="高完成度、色彩通透明亮、二次元审美。",
        palette={"shadow": "#2b3a67", "highlight": "#ffffff", "accent": "#ff8a3d"},
        lighting="天光为主, 干净高光",
        contrast="中高, 色块分明",
        texture="平滑, 少颗粒, 赛璐璐阴影",
        lens_language="长焦浅景, 大光圈虚拟感",
        composition="二次元构图, 留白与符号",
        camera_behavior=CameraBehavior.STABILIZED,
        motion_feel=MotionFeel.SMOOTH,
        production_design="二次元场景, 符号化道具",
        post_processing="通透, 高饱和, 干净",
        negative_tendencies=["写实厚涂", "暗沉灰调", "真实噪点"],
        reference_guidance=["参考优质番剧", "干净通透"],
    ),
    StylePackSpec(
        style_key="dynamic_comic_v1",
        style_version="1",
        display_name="动感漫改",
        medium="video",
        description="漫画式分镜、强动态、情绪夸张。",
        palette={"shadow": "#1a1a2e", "highlight": "#fff8e7", "accent": "#ff2a5f"},
        lighting="强对比漫画光, 速度线感",
        contrast="高, 色块边缘分明",
        texture="漫画网点/粗线, 少细节",
        lens_language="广角动态, 夸张机位",
        composition="动势构图, 对角张力",
        camera_behavior=CameraBehavior.HANDHELD,
        motion_feel=MotionFeel.RHYTHMIC,
        production_design="漫画感场景, 符号化",
        post_processing="粗颗粒, 高饱和, 漫画滤镜",
        negative_tendencies=["写实细腻",  "低饱和", "平实构图"],
        reference_guidance=["参考漫画分镜", "动势与速度线"],
    ),
    StylePackSpec(
        style_key="commercial_premium_v1",
        style_version="1",
        display_name="商业高级感",
        medium="video",
        description="高端品牌质感, 讲究光影与物料。",
        palette={"shadow": "#15181c", "highlight": "#f5f2ec", "accent": "#b8934a"},
        lighting="硬光高光, 强调体感与反射",
        contrast="高, 精致层次",
        texture="高级材质, 金属/玻璃/皮革",
        lens_language="微距/长焦, 精密构图",
        composition="产品主体, 留白高级",
        camera_behavior=CameraBehavior.STABILIZED,
        motion_feel=MotionFeel.SMOOTH,
        production_design="干净背景, 高级道具, 品牌色",
        post_processing="精致, 微锐, 低饱和高级",
        negative_tendencies=["生活感杂光", "塑料廉价感", "过度颗粒"],
        reference_guidance=["参考高端品牌广告", "材质与光影"],
    ),
    StylePackSpec(
        style_key="documentary_natural_v1",
        style_version="1",
        display_name="纪实自然",
        medium="video",
        description="自然光、手持、真实生活与自然。",
        palette={"shadow": "#3a3428", "highlight": "#f4efe3", "accent": "#9aa05a"},
        lighting="自然光/天空光, 环境光主导",
        contrast="中低, 柔和真实",
        texture="真实环境, 有机颗粒",
        lens_language="变焦, 观察式, 有时晃动",
        composition="真实抓拍, 非摆拍构图",
        camera_behavior=CameraBehavior.HANDHELD,
        motion_feel=MotionFeel.WEIGHTED,
        production_design="真实场景, 无布景修饰",
        post_processing="低干预, 自然色彩",
        negative_tendencies=["过度滤镜", "摆拍感", "人工布光"],
        reference_guidance=["参考自然/人文纪录片", "真实环境"],
    ),
]
