"""Character + canonical reference registration (P0 §3.1.9)."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, Character, CharacterReference
from app.config import get_settings
from app.consistency.face_policy import approved_face_threshold
from app.consistency.image_embed import embedding_from_image_bytes
from app.execution.artifact_lineage import get_or_create_artifact
from app.execution.models import GraphNode, NodeRun, ProviderOperation
from app.production.service import GraphService
from app.shared.errors import ValidationAppError
from app.storage.minio_store import ObjectStore, get_object_store

CANONICAL_TEMPLATE_KEY = "character-canonical-v1"


@dataclass(frozen=True)
class CharacterWithCanonical:
    character_id: UUID
    asset_id: UUID
    name: str
    canonical_object_key: str
    canonical_artifact_id: UUID
    canonical_content_hash: str
    canonical_mime_type: str
    similarity_threshold: float
    embedding_dim: int


async def create_canonical_generation_run(
    session: AsyncSession,
    *,
    project_id: UUID,
    user_id: UUID,
    name: str,
    prompt: str,
) -> NodeRun:
    """Create the audit-parent Run for canonical generation.

    ProviderOperation requires exactly one non-null of node_run_id/agent_run_id.
    The canonical image is generated by a Provider (Agnes I2I when configured), so
    it needs a legal audit parent before any ProviderOperation is written. This
    creates a minimal one-node canonical graph + running NodeRun to be that parent.
    """
    import hashlib
    from datetime import UTC, datetime
    from uuid import uuid4

    graphs = GraphService(session)
    graph = await graphs.create_graph(
        project_id=project_id,
        scope_type="shot",
        scope_entity_id=uuid4(),
        template_key=CANONICAL_TEMPLATE_KEY,
        created_by=user_id,
        definition={
            "nodes": [
                {"key": "canonical", "type": "keyframe", "display_name": "Canonical"}
            ],
            "edges": [],
        },
    )
    assert graph.current_version_id is not None
    node = GraphNode(
        graph_version_id=graph.current_version_id,
        node_key="canonical",
        node_type="keyframe",
        display_name="Canonical",
        cacheable=False,
    )
    session.add(node)
    await session.flush()
    now = datetime.now(UTC)
    run = NodeRun(
        project_id=project_id,
        graph_version_id=graph.current_version_id,
        graph_node_id=node.id,
        attempt_no=1,
        idempotency_key=f"canonical:{name}:{uuid4()}",
        input_hash=hashlib.sha256(f"{name}|{prompt}".encode()).hexdigest(),
        status="running",
        input_snapshot={
            "purpose": "canonical_image",
            "character_name": name,
            "prompt": prompt,
            "source_commit": get_settings().source_commit,
        },
        output_summary={},
        started_at=now,
        created_by=user_id,
    )
    session.add(run)
    await session.flush()
    return run


async def record_canonical_provider_operation(
    session: AsyncSession,
    *,
    run: NodeRun,
    adapter: object,
    provider_name: str,
    model_name: str,
    prompt: str,
    remote_id: str | None,
) -> ProviderOperation:
    """Persist the ProviderOperation that backs the canonical generation Run."""
    import hashlib
    from datetime import UTC, datetime

    safe_request_summary: dict[str, object] = {
        "purpose": "canonical_image",
        "chars": len(prompt),
        "transport": "text_to_image",
    }
    fingerprint = hashlib.sha256(
        f"canonical:{provider_name}:{model_name}:{safe_request_summary}".encode()
    ).hexdigest()
    op = ProviderOperation(
        node_run_id=run.id,
        attempt_no=run.attempt_no,
        purpose="primary",
        operation_kind="image.canonical.generate",
        actual_provider=provider_name,
        actual_model=model_name,
        provider_operation_id=remote_id,
        protocol_profile=str(getattr(adapter, "protocol_profile", "") or "") or None,
        request_fingerprint=fingerprint,
        status="succeeded",
        request_summary=safe_request_summary,
        response_summary={},
        submitted_at=datetime.now(UTC),
        completed_at=datetime.now(UTC),
    )
    session.add(op)
    await session.flush()
    return op


async def register_lead_character(
    session: AsyncSession,
    *,
    project_id: UUID,
    name: str,
    locked_prompt: str,
    canonical_image_bytes: bytes,
    store: ObjectStore | None = None,
    produced_by_run_id: UUID | None = None,
) -> CharacterWithCanonical:
    """Create character asset + canonical reference with 512-d embedding from image."""
    if not canonical_image_bytes:
        raise ValidationAppError("canonical image required")
    obj = store or get_object_store()
    emb = embedding_from_image_bytes(canonical_image_bytes)
    if len(emb) != 512:
        raise ValidationAppError("embedding dim must be 512")

    asset = Asset(
        project_id=project_id,
        kind="character",
        name=name,
        description=f"Lead character {name}",
        status="active",
        metadata_json={"role": "lead"},
    )
    session.add(asset)
    await session.flush()
    char = Character(
        id=asset.id,
        locked_prompt=locked_prompt,
        negative_prompt="",
        calibration_state="calibrated",
        similarity_threshold=approved_face_threshold(),
    )
    session.add(char)
    await session.flush()

    object_key = f"projects/{project_id}/characters/{asset.id}/canonical.png"
    stored = await obj.put_bytes(
        object_key=object_key,
        data=canonical_image_bytes,
        mime_type="image/png",
    )
    artifact = await get_or_create_artifact(
        session,
        project_id=project_id,
        artifact_type="image",
        object_key=stored.object_key,
        content_hash=stored.content_hash,
        mime_type=stored.mime_type,
        byte_size=stored.byte_size,
        produced_by_run_id=produced_by_run_id,
    )
    ref = CharacterReference(
        character_id=char.id,
        artifact_id=artifact.id,
        object_key=artifact.object_key,
        reference_kind="canonical",
        is_canonical=True,
        face_embedding=emb,
        embedding_model_version="content-hash-v1",
    )
    session.add(ref)
    await session.flush()
    return CharacterWithCanonical(
        character_id=char.id,
        asset_id=asset.id,
        name=name,
        canonical_object_key=artifact.object_key,
        canonical_artifact_id=artifact.id,
        canonical_content_hash=artifact.content_hash,
        canonical_mime_type=artifact.mime_type,
        similarity_threshold=approved_face_threshold(),
        embedding_dim=len(emb),
    )


async def require_canonical_for_shot(
    session: AsyncSession,
    *,
    project_id: UUID,
    character_id: UUID | None = None,
) -> CharacterReference:
    """Reject generation when project lead has no canonical reference."""
    q = (
        select(CharacterReference)
        .join(Character, Character.id == CharacterReference.character_id)
        .join(Asset, Asset.id == Character.id)
        .where(Asset.project_id == project_id)
        .where(CharacterReference.is_canonical.is_(True))
    )
    if character_id is not None:
        q = q.where(Character.id == character_id)
    ref = (await session.execute(q.limit(1))).scalar_one_or_none()
    if ref is None:
        raise ValidationAppError("CANONICAL_REFERENCE_REQUIRED")
    if ref.artifact_id is None or not ref.object_key or not ref.face_embedding:
        raise ValidationAppError("CANONICAL_REFERENCE_REQUIRED")
    return ref
