"""Character + canonical reference registration (P0 §3.1.9)."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, Character, CharacterReference
from app.config import get_settings
from app.execution.artifact_lineage import get_or_create_artifact
from app.execution.models import Artifact, GraphNode, NodeRun, ProviderOperation
from app.production.service import GraphService
from app.shared.errors import ValidationAppError
from app.storage.minio_store import ObjectStore, get_object_store

CANONICAL_TEMPLATE_KEY = "character-canonical-v1"


@dataclass(frozen=True)
class CharacterWithCanonical:
    character_id: UUID
    asset_id: UUID
    name: str
    canonical_object_key: str
    canonical_artifact_id: UUID
    canonical_content_hash: str
    canonical_mime_type: str


@dataclass(frozen=True)
class ProjectCanonicalBinding:
    character_id: UUID
    name: str
    reference_id: UUID
    artifact: Artifact
    source_run: NodeRun


async def create_canonical_generation_run(
    session: AsyncSession,
    *,
    project_id: UUID,
    user_id: UUID,
    name: str,
    prompt: str,
) -> NodeRun:
    """Create the audit-parent Run for canonical generation.

    ProviderOperation requires exactly one non-null of node_run_id/agent_run_id.
    The canonical image is generated by a Provider (Agnes I2I when configured), so
    it needs a legal audit parent before any ProviderOperation is written. This
    creates a minimal one-node canonical graph + running NodeRun to be that parent.
    """
    import hashlib
    from datetime import UTC, datetime
    from uuid import uuid4

    graphs = GraphService(session)
    graph = await graphs.create_graph(
        project_id=project_id,
        scope_type="shot",
        scope_entity_id=uuid4(),
        template_key=CANONICAL_TEMPLATE_KEY,
        created_by=user_id,
        definition={
            "nodes": [
                {"key": "canonical", "type": "keyframe", "display_name": "Canonical"}
            ],
            "edges": [],
        },
    )
    assert graph.current_version_id is not None
    node = GraphNode(
        graph_version_id=graph.current_version_id,
        node_key="canonical",
        node_type="keyframe",
        display_name="Canonical",
        cacheable=False,
    )
    session.add(node)
    await session.flush()
    now = datetime.now(UTC)
    run = NodeRun(
        project_id=project_id,
        graph_version_id=graph.current_version_id,
        graph_node_id=node.id,
        attempt_no=1,
        idempotency_key=f"canonical:{name}:{uuid4()}",
        input_hash=hashlib.sha256(f"{name}|{prompt}".encode()).hexdigest(),
        status="running",
        input_snapshot={
            "purpose": "canonical_image",
            "character_name": name,
            "prompt": prompt,
            "source_commit": get_settings().source_commit,
        },
        output_summary={},
        started_at=now,
        created_by=user_id,
    )
    session.add(run)
    await session.flush()
    return run


async def record_canonical_provider_operation(
    session: AsyncSession,
    *,
    run: NodeRun,
    adapter: object,
    provider_name: str,
    model_name: str,
    prompt: str,
    remote_id: str | None,
) -> ProviderOperation:
    """Persist the ProviderOperation that backs the canonical generation Run."""
    import hashlib
    from datetime import UTC, datetime

    safe_request_summary: dict[str, object] = {
        "purpose": "canonical_image",
        "chars": len(prompt),
        "transport": "text_to_image",
    }
    fingerprint = hashlib.sha256(
        f"canonical:{provider_name}:{model_name}:{safe_request_summary}".encode()
    ).hexdigest()
    op = ProviderOperation(
        node_run_id=run.id,
        attempt_no=run.attempt_no,
        purpose="primary",
        operation_kind="image.canonical.generate",
        actual_provider=provider_name,
        actual_model=model_name,
        provider_operation_id=remote_id,
        protocol_profile=str(getattr(adapter, "protocol_profile", "") or "") or None,
        request_fingerprint=fingerprint,
        status="succeeded",
        request_summary=safe_request_summary,
        response_summary={},
        submitted_at=datetime.now(UTC),
        completed_at=datetime.now(UTC),
    )
    session.add(op)
    await session.flush()
    return op


async def register_lead_character(
    session: AsyncSession,
    *,
    project_id: UUID,
    name: str,
    locked_prompt: str,
    canonical_image_bytes: bytes,
    store: ObjectStore | None = None,
    produced_by_run_id: UUID | None = None,
) -> CharacterWithCanonical:
    """Create a character and immutable Canonical reference Artifact."""
    if not canonical_image_bytes:
        raise ValidationAppError("canonical image required")
    obj = store or get_object_store()

    asset = Asset(
        project_id=project_id,
        kind="character",
        name=name,
        description=f"Lead character {name}",
        status="active",
        metadata_json={"role": "lead"},
    )
    session.add(asset)
    await session.flush()
    char = Character(
        id=asset.id,
        locked_prompt=locked_prompt,
        negative_prompt="",
        calibration_state="awaiting_visual_review",
    )
    session.add(char)
    await session.flush()

    object_key = f"projects/{project_id}/characters/{asset.id}/canonical.png"
    stored = await obj.put_bytes(
        object_key=object_key,
        data=canonical_image_bytes,
        mime_type="image/png",
    )
    artifact = await get_or_create_artifact(
        session,
        project_id=project_id,
        artifact_type="image",
        object_key=stored.object_key,
        content_hash=stored.content_hash,
        mime_type=stored.mime_type,
        byte_size=stored.byte_size,
        produced_by_run_id=produced_by_run_id,
    )
    ref = CharacterReference(
        character_id=char.id,
        artifact_id=artifact.id,
        object_key=artifact.object_key,
        reference_kind="canonical",
        is_canonical=True,
    )
    session.add(ref)
    await session.flush()
    return CharacterWithCanonical(
        character_id=char.id,
        asset_id=asset.id,
        name=name,
        canonical_object_key=artifact.object_key,
        canonical_artifact_id=artifact.id,
        canonical_content_hash=artifact.content_hash,
        canonical_mime_type=artifact.mime_type,
    )


async def promote_project_character_canonical(
    session: AsyncSession,
    *,
    project_id: UUID,
    name: str,
    locked_prompt: str,
    artifact: Artifact,
    source_run: NodeRun,
) -> ProjectCanonicalBinding:
    """Promote one accepted trial image into the project's canonical set."""
    if (
        artifact.project_id != project_id
        or artifact.artifact_type != "image"
        or artifact.storage_state != "available"
        or artifact.deleted_at is not None
        or artifact.produced_by_run_id != source_run.id
        or source_run.project_id != project_id
        or source_run.result_artifact_id != artifact.id
        or source_run.status not in {"completed", "cached", "completed_after_cancel"}
    ):
        raise ValidationAppError("accepted canonical Artifact lineage is invalid")

    asset = await session.scalar(
        select(Asset).where(
            Asset.project_id == project_id,
            Asset.kind == "character",
            Asset.name == name,
        )
    )
    character: Character
    if asset is None:
        asset = Asset(
            project_id=project_id,
            kind="character",
            name=name,
            description=f"Fictional character {name}",
            status="active",
            metadata_json={"source": "director_trial"},
        )
        session.add(asset)
        await session.flush()
        character = Character(
            id=asset.id,
            locked_prompt=locked_prompt,
            negative_prompt="",
            calibration_state="creator_accepted_trial",
        )
        session.add(character)
        await session.flush()
    else:
        existing_character = await session.get(Character, asset.id)
        if existing_character is None:
            raise ValidationAppError("character Asset has no Character row")
        character = existing_character
        character.locked_prompt = locked_prompt
        character.calibration_state = "creator_accepted_trial"

    existing_refs = list(
        (
            await session.execute(
                select(CharacterReference).where(
                    CharacterReference.character_id == character.id,
                    CharacterReference.is_canonical.is_(True),
                )
            )
        ).scalars()
    )
    for existing in existing_refs:
        if existing.artifact_id == artifact.id:
            return ProjectCanonicalBinding(
                character_id=character.id,
                name=name,
                reference_id=existing.id,
                artifact=artifact,
                source_run=source_run,
            )
        existing.is_canonical = False

    reference = CharacterReference(
        character_id=character.id,
        artifact_id=artifact.id,
        object_key=artifact.object_key,
        reference_kind="canonical",
        is_canonical=True,
    )
    session.add(reference)
    await session.flush()
    return ProjectCanonicalBinding(
        character_id=character.id,
        name=name,
        reference_id=reference.id,
        artifact=artifact,
        source_run=source_run,
    )


async def project_canonical_bindings(
    session: AsyncSession,
    *,
    project_id: UUID,
    names: list[str],
) -> dict[str, ProjectCanonicalBinding]:
    """Return exact project-level Canonical bindings for the requested cast."""
    requested = list(dict.fromkeys(names))
    rows = list(
        (
            await session.execute(
                select(Asset, Character, CharacterReference, Artifact, NodeRun)
                .join(Character, Character.id == Asset.id)
                .join(CharacterReference, CharacterReference.character_id == Character.id)
                .join(Artifact, Artifact.id == CharacterReference.artifact_id)
                .join(NodeRun, NodeRun.id == Artifact.produced_by_run_id)
                .where(
                    Asset.project_id == project_id,
                    Asset.kind == "character",
                    Asset.name.in_(requested),
                    CharacterReference.is_canonical.is_(True),
                )
            )
        ).tuples()
    )
    result: dict[str, ProjectCanonicalBinding] = {}
    for asset, character, reference, artifact, source_run in rows:
        if (
            artifact.project_id != project_id
            or artifact.artifact_type != "image"
            or artifact.storage_state != "available"
            or artifact.deleted_at is not None
            or artifact.produced_by_run_id != source_run.id
            or source_run.project_id != project_id
            or source_run.result_artifact_id != artifact.id
            or source_run.status not in {"completed", "cached", "completed_after_cancel"}
        ):
            continue
        if asset.name in result:
            raise ValidationAppError("multiple active Canonical references exist for a character")
        result[asset.name] = ProjectCanonicalBinding(
            character_id=character.id,
            name=asset.name,
            reference_id=reference.id,
            artifact=artifact,
            source_run=source_run,
        )
    missing = [name for name in requested if name not in result]
    if missing:
        raise ValidationAppError(
            "project Canonical reference set is incomplete",
            details={"code": "CANONICAL_REFERENCE_REQUIRED", "characters": missing},
        )
    return result


async def require_canonical_for_shot(
    session: AsyncSession,
    *,
    project_id: UUID,
    character_id: UUID | None = None,
) -> CharacterReference:
    """Reject generation when project lead has no canonical reference."""
    q = (
        select(CharacterReference)
        .join(Character, Character.id == CharacterReference.character_id)
        .join(Asset, Asset.id == Character.id)
        .where(Asset.project_id == project_id)
        .where(CharacterReference.is_canonical.is_(True))
    )
    if character_id is not None:
        q = q.where(Character.id == character_id)
    ref = (await session.execute(q.limit(1))).scalar_one_or_none()
    if ref is None:
        raise ValidationAppError("CANONICAL_REFERENCE_REQUIRED")
    if ref.artifact_id is None or not ref.object_key:
        raise ValidationAppError("CANONICAL_REFERENCE_REQUIRED")
    return ref
