export const timelineCopy = {
  timeline: "可视时间线",
  clip: "片段",
  crop: { in: "裁短入点", out: "裁短出点" },
  cropHint: "拖动裁短；Enter / 空格裁短 0.1 秒；Escape 取消拖动，保留变速比例",
  zoom: "时间线缩放",
  invalidGeometry: "片段时长或转场无效，请在检查器修正后更新预览。",
  geometryDraft: "草稿时间刻度 · 保存与预览仍需服务端校验",
  geometryCompiled: "已核对时间刻度 · 与剪辑预览一致",
  muteToggle: "静音配音",
  subtitleToggle: "显示字幕",
  video: "视频轨",
  audio: "配音轨",
  subtitles: "字幕轨",
  source: "源素材",
  composition: "剪辑预览",
  draft: "未保存草稿",
  saved: "已保存时间线",
  updatePreview: "更新剪辑预览",
  preparing: "正在核对剪辑预览…",
  stale: "时间线已修改，请更新剪辑预览。",
  noPreview: "更新预览以核对裁切、顺序、配音与字幕。预览不会保存或导出。",
  playback: "剪辑预览视频",
  audioPlayback: "剪辑预览配音",
  play: "播放剪辑",
  pause: "暂停剪辑",
  mute: "此片段静音",
  noAudio: "暂无配音",
  defaultAudio: "沿用既有镜头配音",
  noSubtitle: "无字幕",
  sourceNotice: "播放原始素材；此播放器不应用时间线效果。",
  dragHint: "拖动片段可排序；选中后 Alt + 左/右方向键执行相同操作。字幕与配音跟随片段。",
  playerError: "预览素材读取或播放失败，请检查素材后重试。",
  unsupported: "当前剪辑预览无法呈现以下效果，请使用源素材或实际导出检查：",
  unsupportedReasons: {
    crossfade: "交叉淡化（保留导出能力）",
    background_music: "背景音乐混音（保留导出能力）",
    voice_unavailable: "所需镜头配音尚无匹配的正式合成证据；可关联已有音频或显式静音",
  } as Record<string, string>,
};
